# Generated by Django 4.2.24 on 2025-09-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_problemdata_input_filename_problemdata_io_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='key',
            field=models.CharField(help_text='The identifier for this language; the same as its executor id for judges.', max_length=15, unique=True, verbose_name='short identifier'),
        ),
    ]
