# Generated by Django 4.2.24 on 2026-06-24 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_alter_contest_format_name_themisextensionmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DMOJ: Modern Online Judge', max_length=100, verbose_name='Site Name')),
                ('site_short_name', models.CharField(default='DMOJ', max_length=20, verbose_name='Site Short Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='Logo Image')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='site_favicon/', verbose_name='Favicon')),
                ('welcome_message', models.TextField(blank=True, default='', verbose_name='Welcome Message (Markdown)')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+$', 'Contest id must be ^[a-zA-Z0-9_-]+$')], verbose_name='contest id'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='A short, unique code for the problem, used in the URL after /problem/', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+$', 'Problem code must be ^[a-zA-Z0-9_-]+$')], verbose_name='problem code'),
        ),
    ]
