# Generated by Django 4.2.24 on 2026-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0153_siteconfiguration_alter_contest_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Meta Keywords'),
        ),
    ]
