# Generated by Django 4.2.24 on 2026-07-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0154_siteconfiguration_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='source name')),
            ],
            options={
                'verbose_name': 'quiz source',
                'verbose_name_plural': 'quiz sources',
            },
        ),
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='tag name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'quiz tag',
                'verbose_name_plural': 'quiz tags',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='session key')),
                ('questions', models.JSONField(default=list, verbose_name='questions ordered list')),
                ('answers', models.JSONField(default=dict, verbose_name='user answers')),
                ('current_index', models.IntegerField(default=0, verbose_name='current index')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('score', models.FloatField(default=0.0, verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'quiz session',
                'verbose_name_plural': 'quiz sessions',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='question content')),
                ('type', models.CharField(choices=[('choice', 'Trắc nghiệm'), ('tf', 'Chùm Đúng/Sai')], default='choice', max_length=20, verbose_name='question type')),
                ('difficulty', models.CharField(choices=[('easy', 'Nhận biết'), ('medium', 'Thông hiểu'), ('hard', 'Vận dụng'), ('very_hard', 'Vận dụng cao')], default='easy', max_length=20, verbose_name='difficulty')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='judge.quizsource', verbose_name='source')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='judge.quiztag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'quiz question',
                'verbose_name_plural': 'quiz questions',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='label')),
                ('content', models.TextField(verbose_name='option content')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='judge.quizquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'quiz option',
                'verbose_name_plural': 'quiz options',
                'ordering': ['label'],
            },
        ),
    ]
