# Generated by Django 4.2.24 on 2026-07-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0155_quizsource_quiztag_quizsession_quizquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='quiz_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Quiz/Exam Features'),
        ),
    ]
