# Generated by Django 4.2.24 on 2026-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_expand_quizsource_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='avatar filename'),
        ),
    ]
