# Generated by Django 4.2.30 on 2026-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS rules to apply across the site.', verbose_name='Custom CSS'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_js',
            field=models.TextField(blank=True, default='', help_text='Custom JavaScript or script tags to inject before </body>.', verbose_name='Custom Javascript'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_override',
            field=models.BooleanField(default=False, help_text='If checked, only the Custom Footer HTML will be displayed, replacing the default footer text.', verbose_name='Override Default Footer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, default='', help_text='Custom HTML content to display in the footer.', verbose_name='Custom Footer HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_style',
            field=models.CharField(blank=True, default='', help_text='Example: width: 120px; height: auto; margin-top: -2px;', max_length=255, verbose_name='Logo Custom Inline CSS'),
        ),
    ]
