# Generated by Django 4.2.30 on 2026-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_siteconfiguration_custom_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsource',
            name='is_strict_anti_cheat',
            field=models.BooleanField(default=False, help_text='Require fullscreen, detect tab switching, and log violations realtime.', verbose_name='strict anti-cheat mode'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='max_violations',
            field=models.IntegerField(default=5, help_text='Maximum violations before auto submit (0 = warning only).', verbose_name='max violations'),
        ),
    ]
