# Generated by Django 4.2.30 on 2026-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0160_quizsource_is_strict_anti_cheat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsource',
            name='access_code',
            field=models.CharField(blank=True, help_text='6-character PIN code for quick student join.', max_length=20, null=True, unique=True, verbose_name='access code / PIN'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Exam closes after this time.', null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='exam_type',
            field=models.CharField(choices=[('in_class', 'Kiểm tra tại lớp'), ('homework', 'Bài tập về nhà'), ('practice', 'Luyện tập tự do')], default='in_class', max_length=20, verbose_name='exam type'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Teacher can toggle this to open or close the exam room anytime.', verbose_name='is active / open for submission'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Randomize choice options (A,B,C,D) order.', verbose_name='shuffle options'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for each student attempt.', verbose_name='shuffle questions'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Exam becomes accessible from this time.', null=True, verbose_name='start time'),
        ),
        migrations.AddField(
            model_name='quizsource',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Specific classes assigned to take this exam.', related_name='assigned_quiz_sources', to='judge.class', verbose_name='target classes'),
        ),
        migrations.AlterField(
            model_name='quizsource',
            name='is_organization_only',
            field=models.BooleanField(default=False, help_text='Only members of selected organizations or classes can view and start this exam.', verbose_name='organization only'),
        ),
    ]
